#!/usr/bin/env node
var readline = require('readline');
var path = require('path');
var wsock = require('websock');
var settings = require('./settings');

var url = process.argv[2]
if(typeof url == "undefined") {
  console.log("Usage: "+path.basename(process.argv[1])+" wss://webserver");
  process.exit(1);
}
var ws = new wsock.connect(url, {agent: {rejectUnauthorized:false}});

var rl = readline.createInterface(process.stdin, process.stdout);
rl.setPrompt('')

ws.on('open', function() {
  rl.on('line', function(answer){
      ws.send(answer); 
    }).on('close', function() {
                       process.exit(0);
                     });
});

ws.on('message', function(data) {
  process.stdout.write(data)
});

ws.on('error', function(data) {
  console.error(data)
});

ws.on('close', function() {
});
